spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8083

employee:
  notification:
    completion-webhook:
      url: http://localhost:8081/api/v1/webhooks/notification-completed

webhook:
  secret: ${WEBHOOK_SECRET:my-local-webhook-secret}